import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import ClientWrapper from "@/components/Wrappers/ClientWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <ClientWrapper>
          <Navbar />
          <main>{children}</main>
        </ClientWrapper>
      </body>
    </html>
  );
}
